trigger:
- main

variables:
  imageName: 'automation-client'
  acrLoginServer: 'bitlancecontainer.azurecr.io'
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'

steps:

# Build + Push Docker image to ACR
- task: Docker@2
  displayName: Build and Push to ACR
  inputs:
    command: buildAndPush
    containerRegistry: 'Bitlance'   # your service connection
    repository: '$(imageName)'
    dockerfile: '$(Build.SourcesDirectory)/client/Dockerfile'
    tags: |
      $(tag)
      latest